name: tests
on: [push]

jobs:
  Unit-Tests:
    name: Python-${{ matrix.python-version }}-${{ matrix.qt-binding }}-${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        qt-binding: [PyQt5, PyQt6, PySide2, PySide6]
        python-version: ['3.8', '3.9', '3.10', '3.11']
        platform: [ubuntu-latest, macos-latest]  # , windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Qt Binding
        run: pip install ${{ matrix.qt-binding }}
      - name: Run Unit Tests
        run: python -m unittest discover -s tests
        env:
          TEST_QT_MODULE: ${{ matrix.qt-binding }}
          PYTHONPATH: src
